name: CI-CD Pipeline

on:
    workflow_dispatch:
    push:
        branches: ["main"]

permissions:
    id-token: write
    contents: read
    actions: read

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup Node.js environmen
              uses: actions/setup-node@v6
              with:
                  node-version: "24"
            - run: |
                  npm ci
                  npm run build

            - name: Upload build artifact
              uses: actions/upload-artifact@v7
              with:
                  name: static-out
                  path: out/

    tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup Node.js environment
              uses: actions/setup-node@v6
              with:
                  node-version: "24"

            - run: |
                  npm ci
                  npm run test

    terraform_plan:
        name: Terraform Plan
        runs-on: ubuntu-latest
        needs: tests

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Azure login
              uses: azure/login@v3
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4
              with:
                  terraform_version: "1.15.2"

            - name: Validate main resources (main)
              run: |
                  cd infrastructure
                  terraform fmt -check -recursive
                  terraform init -backend-config="env/azurerm-config-development.tfbackend"
                  terraform validate

            - name: Terraform plan
              run: |
                  cd infrastructure
                  terraform plan -var-file="env/development.tfvars" -out=tfplan

            - name: Upload plan artifact
              uses: actions/upload-artifact@v7
              with:
                  name: tfplan
                  path: infrastructure/tfplan

    terraform_apply:
        name: Terraform Apply and Deploy
        runs-on: ubuntu-latest
        needs: terraform_plan
        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Azure login
              uses: azure/login@v3
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4
              with:
                  terraform_version: "1.15.2"

            - name: Terraform init
              run: |
                  cd infrastructure
                  terraform init

            - name: Download plan artifact
              uses: actions/download-artifact@v8
              with:
                  name: tfplan
                  path: infrastructure/

            - name: Apply main resources (main)
              run: |
                  cd infrastructure
                  terraform apply -auto-approve tfplan

            - name: Download build artifact
              uses: actions/download-artifact@v8
              with:
                  name: static-out
                  path: out/

            - name: Get API token
              run: |
                  cd infrastructure
                  API_KEY=$(terraform output -raw web_app_api_key)
                  echo "::add-mask::$API_KEY"
                  echo "SWA_API_KEY=$API_KEY" >> $GITHUB_ENV

            - name: Deploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ env.SWA_API_KEY }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  action: "upload"
                  app_location: "out"
                  output_location: ""
                  skip_app_build: true
